apiVersion: v1
kind: Pod
metadata:
  name: botserver
  labels:
    name: botserver
spec:
  containers:
  - name: botserver
    image: eu.gcr.io/botserver-1337/botserver:VERSION
    ports:
    - containerPort: 80
    - containerPort: 5557
    - containerPort: 6555
---
apiVersion: v1
kind: Service
metadata:
  name: botserver
spec:
  type: LoadBalancer
  selector:
    name: botserver
  ports:
  - name: web-80
    protocol: TCP
    port: 80
    targetPort: 80
  - name: swiftbot-5557
    protocol: TCP
    port: 5557
    targetPort: 5557
  - name: mufibot-6555
    protocol: TCP
    port: 6555
    targetPort: 6555