apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: botserver
spec:
  selector:
    matchLabels:
      app: botserver
  replicas: 1
  template:
    metadata:
      name: botserver
      labels:
        app: botserver
    spec:
      containers:
      - name: botserver
        image: eu.gcr.io/botserver-1337/botserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 5557
        - containerPort: 6555
---
apiVersion: v1
kind: Service
metadata:
  name: botserver
spec:
  type: LoadBalancer
  selector:
    app: botserver
  ports:
  - name: web-80
    protocol: TCP
    port: 80
    targetPort: 80
  - name: swiftbot-5557
    protocol: TCP
    port: 5557
    targetPort: 5557
  - name: mufibot-6555
    protocol: TCP
    port: 6555
    targetPort: 6555